baseURL = 'https://nnttai.github.io/'
languageCode = 'en-us'
title = "NNTTai's blog"
theme = 'anatole'
enableEmoji = true
localizedDates = true
enableRobotsTXT = true
summarylength = 10


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[params]
title = "Learn - Do - Share"
author = "Nguyen Nhi Thanh Tai"
description = "If you can't explain it simply-You don't understand it well enough."
profilePicture = "images/profile_pic_edited.jpg"
displayMode = "white"
disableThemeSwitcher = false
contentratio = 0.75
hidesidebar = true
pygmentsCodeFences = true
pygmentsUseClasses = true
customCss = ["css/syntax.css"]
reversepagetitle = true


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/t%C3%A0i-nguy%E1%BB%85n-25556320a/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/nnttai"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
  
  [[menu.main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"

  [[menu.main]]
  name = "Awards"
  weight = 510
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"

  [[menu.main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[menu.main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

[mermail]
enable = true

[params.math]
enable = true
use = "katex"